apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  selector:
    matchLabels:
      app: testapp-pod
  template:
    metadata:
      labels:
        app: testapp-pod
    spec:
      containers:
      - name: testapp-container
        image: testapp:v5
        volumeMounts:
        - name: testconf
          mountPath: "etc/config"
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
      volumes:
      - name: testconf
        configMap:
          name: testapp-config